name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      python_version: "3.9"
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.9, "3.10", "3.11" ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y swig gcc libpulse-dev portaudio19-dev
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .[streaming] -r requirements/test_requirements.txt
      - name: Run Tests
        run: |
          pytest tests
